### ISSUE TITLE
Localstored raise type error at 4.0.0

### ISSUE THREAD

**Issue by heavenshell** [avkonst/hookstate#370]
Hi, Thank you for working v4.0.0

When I update localstored 4.0.0-rc21 to 4.0.0 localstored raise type error.

```typescript
type Foo = {
  name: string
}
const initialState = {
  name: '',
}

export const useNameState = () => {
  const state = useHookstate<Foo>(
    initialState,
    localstored({
      key: 'registration-key',
    })
  )
  return state
}
```

```
error TS2345: Argument of type '{ key: string; }' is not assignable to parameter of type '{ key?: string | undefined; engine: Stor
eEngine; initializer: () => Promise<Foo>; }'.
```
<img width="552" alt="Screenshot 2022-12-26 18 23 16" src="https://user-images.githubusercontent.com/56591/209532345-6b04014f-5d2b-44c7-bf95-e585de2f747d.png">

I refered with document.
https://hookstate.js.org/docs/extensions-localstored

localstored 4.0.0-rc21 works fine.

Regards.

**Comment by avkonst** [comment]
Yes, my bad. Will be fixed

**Comment by avkonst** [comment]
released in 4.0.1
